logging.level:
  org.springframework.transaction: TRACE
  org.springframework.orm.jpa: TRACE
  org.hibernate.SQL: DEBUG
  org.hibernate.orm.jdbc.bind: TRACE
  org.hibernate.type.descriptor: TRACE

spring.application.name: RequiresNew
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: test
    password: test

### JPA
spring.jpa:
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      show_sql: false
      format_sql: true
      use_sql_comments: true
      highlight_sql: true
  hibernate:
    ddl-auto: none
  generate-ddl: false